export const THEME = {
  lightTheme: {
    colors: {
      backgroundDark: "#363740",
      backgroundLight: "#f7f8fc",
      white: "#ffffff",
      cellHover: "rgba(247, 248, 255, 1)",
      mainBlue: "#3751ff",
      mainBlueHover: "#0021ff",
      svgHover: "#dde2ff",
      hoverWhite: "#ffffff",
      grayscaleGray: "#9fa2b4",
      addButton: "#ffffff",
      addButtonText: "#3751ff",
      toggleMode: "#ebebeb",
      subGray: "#9fa2b4",
      menuItemSVG: "#9fa2b4",
      popupBlack: "#252733",
      popupHover: "#ffffff",
      popupBackground: "#c5c7cd",
      grayscaleDark: "#4b506d",
      grayscaleHighlight: "#4b506d",
      grayscaleLight: "#c5c7cd",
      grayscaleLightest: "#f0f1f7",
      disabledArrow: "#f0f1f7",
      grayscaleExtra_light: "#fcfdfe",
      grayscaleBlack: "#252733",
      digitColor: "#252733",
      inputText: "#252733",
      grayscaleSidebar: "#a4a6b3",
      grayscaleDivider: "#dfe0eb",
      avatarBorder: "#dfe0eb",
      lightBlue: "#dde2ff",
      red: "#f12b2c",
      yellow: "#fec400",
      green: "#29cc97",
      popLabel: "rgba(54, 55, 64, 0.60)",
      avatarBG: "#676a7c",
    },
  },
  darkTheme: {
    colors: {
      backgroundDark: "#363740",
      backgroundLight: "#5f616f",
      white: "#676a7d",
      cellHover: "#7b7e91",
      mainBlue: "#3751ff",
      mainBlueHover: "#0021ff",
      svgHover: "#f12b2c",
      hoverWhite: "#ffffff",
      grayscaleGray: "#ffffff",
      addButton: "#2f46dd",
      addButtonText: "#ffffff",
      toggleMode: "#363740",
      subGray: "#a9abb7",
      menuItemSVG: "#9fa2b4",
      popupBlack: "#252733",
      popupHover: "#252733",
      popupBackground: "#c5c7cd",
      grayscaleDark: "#ffffff",
      grayscaleHighlight: "#17181a",
      grayscaleLight: "#ffffff",
      grayscaleLightest: "#f0f1f7",
      disabledArrow: "#83848b",
      grayscaleExtra_light: "#edebeb",
      grayscaleBlack: "#ffffff",
      digitColor: "#252733",
      inputText: "#252733",
      grayscaleSidebar: "#a4a6b3",
      grayscaleDivider: "#515151",
      avatarBorder: "#dfe0eb",
      lightBlue: "#dde2ff",
      red: "#f12b2c",
      yellow: "#fec400",
      green: "#29cc97",
      popLabel: "rgba(54, 55, 64, 0.60)",
      avatarBG: "#c9cad1",
    },
  },
  weight: {
    normal: 400,
    mid_bold: 600,
    bold: 700,
  },
  size: {
    small: "12px",
    normal: "16px",
    normalBig: "19px",
    large: "24px",
    xLarge: "40px",
  },

  border: {
    radius: {
      normal: "8px",
    },
  },

  letterSpacing: {
    4: "0.4px",
    3: "0.3px",
    2: "0.2px",
  },
};
